### ISSUE TITLE
Green nicht mehr nutzbar nach Anzeigen vom Tracker

### ISSUE THREAD

**Issue by MrEbbinghaus** [ProPra16/programmierpraktikum-abschlussprojekt-halt-doch-einfach-mal-dein-maul#11]
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
....
Caused by: java.lang.NullPointerException
    at de.hhu.propra16.TDDT.GreenValidator.BadTest(GreenValidator.java:46)
    at de.hhu.propra16.TDDT.GreenValidator.<init>(GreenValidator.java:24)
    at de.hhu.propra16.TDDT.Controller.GREEN(Controller.java:123)

**Comment by asfer100** [comment]
Pull bitte die neuste Version.
Der Fehler sollte behoben sein.

**Comment by MrEbbinghaus** [comment]
Habe um 17:37:11 gepullt. Also nach dem letzten commit

**Comment by mupek100** [comment]
Die Variable Error ist nie null ...

**Comment by MrEbbinghaus** [comment]
Bekomme es gerade auch nicht reproduziert. 

Fakt ist: Ich habe die ganze Konsole voll von Exceptions.

Aber naja. scheint ja nur ein Randfall zu sein, mal sehen ob ich es wieder hinbekomme

**Comment by asfer100** [comment]
Die Stelle wird jetzt abgefangen.
Kann mir aber diesen Fehler nicht erklären.
